apply plugin: 'com.android.application'
import java.text.SimpleDateFormat

apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'
apply plugin: 'org.jetbrains.kotlin.android'

def getCommitCount = { ->
    return providers.exec { commandLine 'git', 'rev-list', '--count', 'HEAD' }.standardOutput.asText.get().trim().toInteger()
}
def getBranchName = { ->
    return providers.exec { commandLine 'git', 'symbolic-ref', '--short', 'HEAD' }.standardOutput.asText.get().trim()
}
def getShortGitCommitSha = { ->
    return providers.exec { commandLine 'git', 'rev-parse', '--short', 'HEAD' }.standardOutput.asText.get().trim()
}

android {
    namespace = 'org.firstinspires.ftc.teamcode'
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ["-language-version", "1.9", "-api-version", "1.9"]
    }
    packagingOptions { jniLibs.useLegacyPackaging true }
    buildFeatures.buildConfig true

    defaultConfig {
        versionName getBranchName() + "_" + getCommitCount() + "_" + getShortGitCommitSha()
        buildConfigField "String", "APP_BUILD_TIME", '"' + (new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.ROOT).format(new Date())) + '"'
        buildConfigField "boolean", "IS_PRODUCTION", "false"
    }
}

dependencies {
    implementation project(':FtcRobotController')
    implementation 'com.bylazar:fullpanels:1.0.9'
    implementation 'androidx.core:core-ktx:1.8.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
    androidTestImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'

    // Combined PedroPathing dependencies
    implementation 'com.pedropathing:core:3.0.1'
    implementation 'com.pedropathing:ftc:2.1.2'
    implementation 'com.pedropathing:telemetry:1.0.0'
    implementation 'com.pedropathing:revhub:3.0.1'
    implementation 'com.pedropathing:tuning:1.0.2'

    implementation("org.jetbrains.kotlin:kotlin-stdlib") { version { strictly("2.1.21") } }
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8") { version { strictly("2.1.21") } }
}

task compilePedroPaths(type: Exec) {
    group = 'pedro'
    description = 'Compiles custom exported .pp visual files into clean Java autonomous layouts natively.'
    outputs.upToDateWhen { false }
    commandLine System.getProperty('os.name').toLowerCase().contains('windows') ? ['cmd', '/c', "java src/main/java/org/firstinspires/ftc/teamcode/InitializeAutonomousFiles.java"] : ['java', 'src/main/java/org/firstinspires/ftc/teamcode/InitializeAutonomousFiles.java']
}

afterEvaluate {
    tasks.findByName('preBuild')?.dependsOn compilePedroPaths
}
